name: hugegraph-hubble ci

on:
  push:
    branches:
      - master
      - /^release-.*$/
      - /^test-.*$/
      - /^v[0-9]\..*$/
  pull_request:
    branches:
      - master
      - /^release-.*$/
      - /^test-.*$/
      - /^v[0-9]\..*$/

env:
  TRAVIS_DIR: hubble-dist/assembly/travis
  SERVER_VERSION: 0.12.0

jobs:
  hubble-ci:
    runs-on: ubuntu-20.04
    steps:
      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      # we also should cache python & yarn & downloads to avoid useless work
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Compile
        run: |
          mvn clean compile -Dmaven.javadoc.skip=true | grep -v "Downloading\|Downloaded"
          sudo pip install -r ${TRAVIS_DIR}/requirements.txt

      - name: Prepare env and service
        run: |
          $TRAVIS_DIR/download-hugegraph.sh $SERVER_VERSION
          $TRAVIS_DIR/hugegraph-server1/install-hugegraph.sh $SERVER_VERSION
          $TRAVIS_DIR/hugegraph-server2/install-hugegraph.sh $SERVER_VERSION
          $TRAVIS_DIR/install-hugegraph-hubble.sh
          jps

      - name: Unit test
        run: mvn test -P unit-test

      - name: API test
        run: $TRAVIS_DIR/run-api-test.sh

      # Do we need it?
      - name: Build Report
        run: $TRAVIS_DIR/build-report.sh

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: target/site/jacoco/jacoco.xml
